name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg:
          - DiffEqProblemLibrary
          - DAEProblemLibrary
          - DDEProblemLibrary
          - JumpProblemLibrary
          - ODEProblemLibrary
          - SDEProblemLibrary
        version:
          - '1'
          - '1.6'
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: "${{ matrix.pkg == 'DiffEqProblemLibrary' && '@.' || 'lib/${{ matrix.pkg }}' }}"
      - uses: julia-actions/julia-runtest@v1
        with:
          project: "${{ matrix.pkg == 'DiffEqProblemLibrary' && '@.' || 'lib/${{ matrix.pkg }}' }}"
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
